### ISSUE TITLE
Generalize "Girder" styling of login templates and allow it to be overidden

### ISSUE THREAD

**Issue by brianhelba** [girder/django-girder-style#30]

**Comment by brianhelba** [comment]
@jtomeck Find a better default background.

**Comment by brianhelba** [comment]
@jtomeck Can you also replace the `Girder_v2.png` image with a combination of actual text and a logo? That way, we can fetch the text from the site name, similar to #8.

**Comment by jtomeck** [comment]
@brianhelba sounds good. I'll be taking care of this tomorrow (just to give you a status and an idea of time)
