### ISSUE TITLE
Add development banner

### ISSUE THREAD

**Issue by danlamanna** [girder/django-girder-style#9]

**Comment by brianhelba** [comment]
I can do something like this:
![image](https://user-images.githubusercontent.com/1282879/113589177-11a29980-95ff-11eb-826a-1c50fb00a1f5.png)

but I realized it may not actually be necessary, given that we always have the Django Debug Toolbar tab showing in development mode too.

@danlamanna What do you think?

**Comment by brianhelba** [comment]
The code for the banner is:
```django
{% if debug %}<div class="bg-yellow-300 text-center text-sm font-bold uppercase">Development Mode</div>{% endif %}
```

**Comment by danlamanna** [comment]
I'm fine with closing this out then. I would at some point like to tackle the issue of not accidentally making changes on production since prod/sandbox/dev tabs are often open at the same time.

**Comment by brianhelba** [comment]
Closing for now.
